winterhut/models/Post.py
from datetime import datetime
from winterhut import db


class Post(db.Model):
    __tablename__ = 'posts'
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(100), nullable=False)
    date_posted = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    content = db.Column(db.Text, nullable=False)
    is_draft = db.Column(db.Boolean, default=False, nullable=False)
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'), nullable=False)

    def __repr__(self):
        return f"Post('{self.title}', '{self.date_posted}')"

    def dump_as_json(self):
        return {
            "id": f"{self.id}",
            "title": f"{self.title}",
            "date_posted": f"{self.date_posted.isoformat()}",
            "content": f"{self.content}",
            "is_draft": f"{self.is_draft}",
            "user_id": f"{self.user_id}"
        }

    def load_from_json(self, json):
        print(json)
        self.id = json.get('id')
        self.title = json.get('title')
        self.date_posted = datetime.fromisoformat(json.get('date_posted'))
        self.content = json.get('content')
        self.is_draft = json.get('is_draft')
        self.user_id = json.get('user_id')

winterhut/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired


class PostForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    content = TextAreaField('Content', validators=[DataRequired()])
    save_as_draft = SubmitField('Save as Draft')
    submit = SubmitField('Post')

winterhut/main/routes.py
import json
from datetime import datetime
import ast
from flask import Blueprint, request, render_template, flash, url_for
from flask_login import current_user
from werkzeug.utils import redirect
import os
import logging
from winterhut import db
from winterhut.models.IpBan import IpBan
from winterhut.models.Post import Post
from winterhut.main.forms import IpBanForm, ImporterForm
from winterhut.utils.importer import Importer

main = Blueprint('main', __name__)
log = logging.getLogger()


@main.route("/")
@main.route("/page/<int:page>")
def home_page(page=1):
    log.info(f"Landing page requested")
    page_from_url = page
    posts = Post.query.filter_by(is_draft=0).order_by(Post.date_posted.desc())\
        .paginate(page=page_from_url, per_page=1)
    return render_template('home.html', title="Winter's Hut", blog_posts=posts, page_from_url=page_from_url)


@main.route("/level80paladin")
def cv_page():
    log.info(f"CV page requested")
    return render_template('cv.html')


@main.route("/ban_ip", methods=["GET", "POST"])
def ban_ip_page():
    log.info(f"Ban IP page requested")
    if not current_user.is_authenticated:
        log.warning(f"User requesting page is not authenticated, returning to login page")
        flash("You must be logged in to see this page.")
        return redirect(url_for('users.login_page'))
    form = IpBanForm()
    if form.validate_on_submit():
        ip_ban = IpBan(ip=form.ip_address.data, login_attempts=5)
        db.session.add(ip_ban)
        db.session.commit()
        log.info(f"Ban IP form validated, {ip_ban.ip} banned")
        flash(f"IP address '{ip_ban.ip}' banned successfully.")
    return render_template('ban_ip.html', form=form)


@main.route("/importer", methods=["GET", "POST"])
def importer_page():
    log.info(f"Importer page requested")
    if not current_user.is_authenticated:
        log.warning(f"User requesting page is not authenticated, returning to login page")
        flash("You must be logged in to see this page.")
        return redirect(url_for('users.login_page'))
    form = ImporterForm()
    if form.validate_on_submit():
        uploaded_file = request.files['file']
        uploaded_file.save(os.path.join('winterhut/static/', uploaded_file.filename))
        return redirect(url_for('main.importer_data_page', file=f"{uploaded_file.filename}"))
    return render_template('importer_main.html', form=form)


@main.route("/importer_data", methods=["GET", "POST"])
def importer_data_page():
    file = request.args['file']
    file_path = os.path.join("winterhut", "static", file)
    file = open(file_path)
    importer = Importer(file)
    json_data = importer.load_file_content()
    articles = json_data.get('articles')
    prepared_articles = []
    for article_id, article_data in articles.items():
        article_post = Post()
        article_post.title = article_data.get('title')
        article_post.content = article_data.get('content')
        article_post.date_posted = datetime.fromisoformat(article_data.get('published_date'))
        article_post.is_draft = 1
        article_post.user_id = 1
        setattr(article_post, "json_id", article_id)
        prepared_articles.append(article_post)
    return render_template('importer_data.html', data=prepared_articles, file_path=file_path)


@main.route("/preview")
def preview_post_page():
    post_id = request.args['post_id']
    file_path = request.args['file_path']
    file = open(file_path)
    importer = Importer(file)
    json_data = importer.load_file_content()
    articles = json_data.get('articles')
    for article_id, article_data in articles.items():
        if article_id == post_id:
            article_post = Post()
            article_post.title = article_data.get('title')
            article_post.content = article_data.get('content')
            article_post.date_posted = datetime.fromisoformat(article_data.get('published_date'))
            article_post.is_draft = 1
            article_post.user_id = 1
    return render_template('post.html', post=article_post, preview=1)


@main.route("/import")
def import_data():
    file_path = request.args['file_path']
    file = open(file_path)
    importer = Importer(file)
    json_data = importer.load_file_content()
    articles = json_data.get('articles')
    for article_id, article_data in articles.items():
        article_post = Post()
        article_post.title = article_data.get('title')
        article_post.content = article_data.get('content')
        article_post.date_posted = datetime.fromisoformat(article_data.get('published_date'))
        article_post.is_draft = 1
        article_post.user_id = 1
        db.session.add(article_post)
        db.session.commit()
    return redirect(url_for('posts.posts_list_page'))

winterhut/posts/routes.py
import logging
from flask import Blueprint, request, render_template, url_for, flash
from flask_login import current_user
from werkzeug.utils import redirect

from winterhut import db
from winterhut.models.Post import Post
from winterhut.posts.forms import PostForm

posts = Blueprint('posts', __name__)
log = logging.getLogger()


@posts.route("/new_post", methods=["GET", "POST"])
def new_post_page():
    log.info(f"New Post page requested")
    if not current_user.is_authenticated:
        log.warning(f"User requesting page is not authenticated, returning to login page")
        flash("You must be logged in to see this page.")
        return redirect(url_for('users.login_page'))
    form = PostForm()
    if form.validate_on_submit():
        if form.save_as_draft.data:
            post = Post(title=form.title.data,
                        content=form.content.data,
                        is_draft=True,
                        user_id=current_user.id)
            log.info(f"Post with id '{post.id}' saved as draft successfully")
            flash("Post saved as draft successfully.")
        else:
            post = Post(title=form.title.data,
                        content=form.content.data,
                        is_draft=False,
                        user_id=current_user.id)
        db.session.add(post)
        db.session.commit()
        log.info(f"Post with id '{post.id}' posted successfully")
        flash("Post created successfully.")
        return redirect(url_for("posts.view_post_page", post_id=post.id))
    return render_template('new_post.html', form=form)


@posts.route("/post/<int:post_id>")
def view_post_page(post_id):
    log.info(f"View Post page requested")
    if current_user.is_authenticated:
        post = Post.query.filter_by(id=post_id).first_or_404()
        if post.is_draft == 1:
            flash("You are viewing a draft post.")
    else:
        post = Post.query.filter_by(id=post_id, is_draft=0).first_or_404()
    return render_template('post.html', post=post)


@posts.route("/post/<int:post_id>/edit", methods=['GET', 'POST'])
def edit_post_page(post_id):
    log.info(f"Edit Post page requested")
    if not current_user.is_authenticated:
        log.warning(f"User requesting page is not authenticated, returning to login page")
        flash("You must be logged in to see this page.")
        return redirect(url_for('users.login_page'))
    post = Post.query.filter_by(id=post_id).first_or_404()
    form = PostForm()
    if form.validate_on_submit():
        if form.save_as_draft.data:
            post.title = form.title.data
            post.content = form.content.data
            post.is_draft = True
            db.session.commit()
            log.info(f"Post with id '{post.id}' saved as draft successfully")
            flash("Post saved as draft successfully.")
        else:
            post.title = form.title.data
            post.content = form.content.data
            post.is_draft = False
            db.session.commit()
            log.info(f"Post with id '{post.id}' edited successfully")
            flash("Post edited successfully.")
        return redirect(url_for("posts.view_post_page", post_id=post.id))
    elif request.method == "GET":
        form.title.data = post.title
        form.content.data = post.content
    return render_template("edit_post.html", title="Edit Post", form=form)


@posts.route("/posts_list")
def posts_list_page():
    log.info(f"Posts list page requested")
    if not current_user.is_authenticated:
        log.warning(f"User requesting page is not authenticated, returning to login page")
        flash("You must be logged in to see this page.")
        return redirect(url_for('users.login_page'))
    view_filter = request.args.get('view', default="all", type=str)
    if view_filter == "all":
        log.info(f"List of all posts requested")
        all_posts = Post.query.order_by(Post.date_posted.desc())
    elif view_filter == "drafts":
        log.info(f"List of only draft posts requested")
        all_posts = Post.query.filter_by(is_draft=1).order_by(Post.date_posted.desc())
    elif view_filter == "live":
        log.info(f"List of only live posts requested")
        all_posts = Post.query.filter_by(is_draft=0).order_by(Post.date_posted.desc())
    else:
        log.warning(f"Unknown URL parameter: {view_filter}, returning all posts")
        flash(f"Unknown URL parameter: {view_filter}")
        return redirect(url_for("posts.posts_list_page"))
    return render_template('posts_list.html', posts=all_posts)


@posts.route("/all_posts")
def all_posts_page():
    log.info(f"All Posts page requested")
    all_posts = Post.query.filter_by(is_draft=0).order_by(Post.date_posted.desc())
    return render_template('all_blog_posts.html', posts=all_posts)

winterhut/templates/all_blog_posts.html
{% extends "layout.html" %}
{% block title %}
    {% if title %}
        {{ title }}
    {% else %}
        Winter's Hut
    {% endif %}
{% endblock %}
{% block body %}
  <div class="all-posts-page">
    <h2>All entries</h2>
    <div class="all-posts-view">
      {% for post in posts %}
        <a class="post-wrapper" href="{{ url_for('posts.view_post_page', post_id=post.id) }}">
            <div class="post-title">
              {{ post.title }}
            </div>
            <div class="post-date">
              {{ post.date_posted.strftime("%b, %Y") }}
            </div>
        </a>
      {% endfor %}
    </div>
  </div>
{% endblock %}

winterhut/templates/ban_ip.html
{% extends "layout.html" %}
{% block title %}
    {% if title %}
        {{ title }}
    {% else %}
        Winter's Hut
    {% endif %}
{% endblock %}
{% block body %}
  <div class="new-ban">
    <form method="POST" action="">
      {{ form.hidden_tag() }}
      <fieldset>
        <h2>Ban an IP Address</h2>
        {% if form.ip_address.errors %}
          {{ form.ip_address(class="form-field ip-address") }}
          <div class="invalid-feedback">
              {% for error in form.ip_address.errors %}
                  <span>{{ error }}</span>
              {% endfor %}
          </div>
        {% else %}
          {{ form.ip_address(class="form-field ip-address", placeholder="Enter IP address here") }}
        {% endif %}
        <div class="options">
        <a class="btn" href="{{ url_for('main.home_page') }}">Cancel</a>
        {{ form.submit(class="form-field btn") }}
        </div>
      </fieldset>
    </form>
  </div>
{% endblock %}

winterhut/templates/banned.html
{% extends "layout.html" %}
{% block title %}
    {% if title %}
        {{ title }}
    {% else %}
        Winter's Hut
    {% endif %}
{% endblock %}

winterhut/templates/cv.html
{% extends "layout.html" %}
{% block title %}
    {% if title %}
        {{ title }}
    {% else %}
        Winter's CV
    {% endif %}
{% endblock %}
{% block body %}
<div class="cv-table">
  <div class="cv-entry">
    <div class="cv-entry-infoblock">
      <h2 class="cv-entry-title">Senior Application Operations Engineer</h2>
      <h4 class="cv-entry-company">Khoros</h4>
      <h5 class="cv-entry-timespan">April 2020 - Present</h5>
    </div>
    <div class="cv-entry-summaryblock">
      History repeats itself they say, so at some point I became a Senior again! Over the period of being in this position, I was largely focused on building new, or improving the existing, automation tools and processes while still providing head-on support and expertise related to the company's products. Up to date, I've had the pleasure to refactor and create countless scripts and a bunch of automation frameworks.
    </div>
  </div>
  <div class="cv-entry">
    <div class="cv-entry-infoblock">
      <h2 class="cv-entry-title">Application Operations Engineer</h2>
      <h4 class="cv-entry-company">Khoros</h4>
      <h5 class="cv-entry-timespan">March 2019 - April 2020</h5>
    </div>
    <div class="cv-entry-summaryblock">
      Down the line, I could fully move to Operations and focus on doing what I love most - tinker with stuff and (hopefully) not break it on a Friday. My main activity was focused on product deployments and providing operational support for the various organizations within the company and handling of the monthly product release cycles as well as the team mates training and mentoring.
    </div>
  </div>
  <div class="cv-entry">
    <div class="cv-entry-infoblock">
      <h2 class="cv-entry-title">Customer Support Analyst</h2>
      <h4 class="cv-entry-company">Lithium Technologies (now Khoros)</h4>
      <h5 class="cv-entry-timespan">August 2017 - March 2019</h5>
    </div>
    <div class="cv-entry-summaryblock">
      Time proved that being a manager is much harder than I ever imagined. Around the same time, the possibility to move to the UK and start working as a frontline technical support engineer popped up and I felt like it'd be worth giving it a shot. At the time, I was focused on the SaaS products of the company, alongside operational support for both customers and teams within the organization.
    </div>
  </div>
  <div class="cv-entry">
    <div class="cv-entry-infoblock">
      <h2 class="cv-entry-title">Manager, Customer Support and QA</h2>
      <h4 class="cv-entry-company">ETI Software</h4>
      <h5 class="cv-entry-timespan">August 2016 – July 2017</h5>
    </div>
    <div class="cv-entry-summaryblock">
      Eventually, the opportunity to try and lead the team arose and I decided to rise to the challenge! My main focus was on team training, automation and modernization of the tooling and processes. Closely working with both customers and management on projects planning, resourcing, delivery and evaluation of the work that's being done.
    </div>
  </div>
  <div class="cv-entry">
    <div class="cv-entry-infoblock">
      <h2 class="cv-entry-title">Senior QA Engineer</h2>
      <h4 class="cv-entry-company">NetMania IT (now ETI Software)</h4>
      <h5 class="cv-entry-timespan">November 2012 – August 2016</h5>
    </div>
    <div class="cv-entry-summaryblock">
      Of course, over time, I became a Senior! My responsibilities changed a little bit - at that point I was a lot more hands-on with customers, project managers and developers. I was still mainly creating and executing test plans based on the customer requirements and expectations, preparing detailed bug reports and working closely with development and management on the tight schedule. On some projects, I also ended up leading a team of 10-12 people, providing consulting and mentoring to team members, outlining projects scope, time and resources allocation.
    </div>
  </div>
  <div class="cv-entry">
    <div class="cv-entry-infoblock">
      <h2 class="cv-entry-title">QA Engineer</h2>
      <h4 class="cv-entry-company">NetMania IT (now ETI Software)</h4>
      <h5 class="cv-entry-timespan">June 2011 – November 2012</h5>
    </div>
    <div class="cv-entry-summaryblock">
      Some time later, I transitioned into a QA Engineer. My main focus was on creating and executing test plans suitable for an agile monthly release cycle, performing manual UI and functionality testing on internal and production environments, improving the QA process to be faster and more efficient, locating, reporting and finding solutions for issues with the latest release.
    </div>
  </div>
  <div class="cv-entry">
    <div class="cv-entry-infoblock">
      <h2 class="cv-entry-title">First Line Support Technician</h2>
      <h4 class="cv-entry-company">NetMania IT (now ETI Software)</h4>
      <h5 class="cv-entry-timespan">July 2010 – June 2011</h5>
    </div>
    <div class="cv-entry-summaryblock">
      My journey begun as a frontline support technician with a general focus on providing technical support over phone, live chat and e-mail or via the company's ticketing system. Occasionally took part of the release QA cycle of the company's products.
    </div>
  </div>
</div>
{% endblock %}

winterhut/templates/edit_post.html
{% extends "layout.html" %}
{% block title %}
    {% if title %}
        {{ title }}
    {% else %}
        Winter's Hut
    {% endif %}
{% endblock %}
{% block body %}
  <div class="new-post">
    <form method="POST" action="">
      {{ form.hidden_tag() }}
      <fieldset>
        <h2>Edit Post</h2>
        <div>
          {% if form.title.errors %}
            {{ form.title(class="form-field title", placeholder="Title") }}
            <div class="invalid-feedback">
                {% for error in form.title.errors %}
                    <span>{{ error }}</span>
                {% endfor %}
            </div>
          {% else %}
            {{ form.title(class="form-field title", placeholder="Title") }}
          {% endif %}
        </div>
        <div>
          {% if form.content.errors %}
            {{ form.content(class="form-field content", placeholder="Post body") }}
            <div class="invalid-feedback">
                {% for error in form.content.errors %}
                    <span>{{ error }}</span>
                {% endfor %}
            </div>
          {% else %}
            {{ form.content(class="form-field content", placeholder="Post body") }}
          {% endif %}
        </div>
        <a class="btn" href="{{ url_for('main.home_page') }}">Cancel</a>
        <div>
          {{ form.submit(class="form-field btn") }}
        </div>
        <div>
          {{ form.save_as_draft(class="form-field btn") }}
        </div>
      </fieldset>
    </form>
  </div>
{% endblock %}

winterhut/templates/home.html
{% extends "layout.html" %}
{% block title %}
    {% if title %}
        {{ title }}
    {% else %}
        Winter's Hut
    {% endif %}
{% endblock %}
{% block body %}
  <div class="home-content">
    {% if blog_posts %}
        {% for post in blog_posts.items %}
            <article class="blog-article">
                <a class="article-title" href="{{ url_for('posts.view_post_page', post_id=post.id)}}">{{ post.title }}</a>
                <small class="article-date-posted">posted at {{ post.date_posted.strftime("%X, %A, %d/%b/%Y") }}</small>
                <div class="article-content">{{ post.content | safe}}</div>
            </article>
        {% endfor %}
    {% else %}
        <p>Uh, no posts here it seems? :(</p>
    {% endif %}
    <section class="author-section">
        <h3 class="author-section-title">$ whoami</h3>
        <p class="author-section-description">Heya, my name's Dimitar but I'm better known as Winter across the interwebz. Occasional gamer, somewhat of a tech enthusiast, adrenaline junkie constantly living on the edge by singing outside of the shower and occasionally leaving the house.</p>
        <p class="author-socials">.. or catch me at:</p>
        <ul>
          <li><a class="btn" href="https://www.linkedin.com/in/dimitarxivanov/">LinkedIn</a></li>
          <li><a class="btn" href="https://github.com/sudosuwinter/">GitHub</a></li>
          <li><a class="btn" href="https://www.instagram.com/sudosuwinter/">Instagram</a></li>
        </ul>
    </section>
  </div>
    <div class="paging">
        {% if blog_posts.has_prev %}
            <a class="btn page-selector-left" href="{{ url_for( 'main.home_page', page=blog_posts.page - 1 ) }}">Previous</a>
        {% endif %}
        {% if blog_posts.has_next %}
            <a class="btn page-selector-right" href="{{ url_for( 'main.home_page', page=blog_posts.page + 1 ) }}">Next</a>
        {% endif %}
    </div>
{% endblock %}

winterhut/templates/importer_data.html
{% extends "layout.html" %}
{% block title %}
    {% if title %}
        {{ title }}
    {% else %}
        Winter's Hut
    {% endif %}
{% endblock %}
{% block body %}
<div class="importer_data">
  <div class="all-posts-page">
      <h4>Reading data from file: {{ file_path }}</h4>
    <div class="all-posts-view">
  {% for post in data %}
      <a class="post-wrapper" href="{{ url_for('main.preview_post_page', post_id=post.json_id, file_path=file_path) }}">
        <div class="post-title">
          {{ post.title }}
        </div>
        <div class="post-date">
          {{ post.date_posted.strftime("%b, %Y") }}
        </div>
    </a>
  {% endfor %}
    </div>
  </div>
    <br>
    <br>
    <a class="btn" href="{{ url_for( 'main.import_data', file_path=file_path ) }}">Import</a>
</div>
{% endblock %}

winterhut/templates/importer_main.html
{% extends "layout.html" %}
{% block title %}
    {% if title %}
        {{ title }}
    {% else %}
        Winter's Hut
    {% endif %}
{% endblock %}
{% block body %}
<div class="importer_main">
  <form method="POST" action="" enctype=multipart/form-data>
    {{ form.hidden_tag() }}
    <fieldset>
      <input type = "file" name = "file" />
      {{ form.submit(class="form-field btn") }}
    </fieldset>
  </form>
</div>
{% endblock %}

winterhut/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="author" content="Dimitar Ivanov">
    <meta name="description" content="Dimitar's small corner in the vast world of the interwebz">

    {% block head %}
    {% endblock %}

    <link rel="stylesheet" href="/static/main.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Merienda&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Raleway:ital,wght@0,400;0,700;1,400;1,700&display=swap" rel="stylesheet">

    <title>
        {% block title %}
        {% endblock %}
    </title>
</head>
<body>
  <div class="main-container">
    <div class="header-title">
      Winter's Hut
    </div>
    <nav class="navigation-bar">
      <div class="nav-left">
        <a class="btn" href="{{ url_for('main.home_page') }}">Home</a>
        <a class="btn" href="{{ url_for('posts.all_posts_page') }}">Blog Posts</a>
        <a class="btn" href="{{ url_for('main.cv_page') }}">XP</a>
      </div>
      <div class="nav-right">
        {% if current_user.is_authenticated %}
          <a class="btn" href="{{ url_for('posts.posts_list_page') }}">Posts List</a>
          <a class="btn" href="{{ url_for('posts.new_post_page') }}">New Post</a>
          <a class="btn" href="{{ url_for('main.ban_ip_page') }}">New IP Ban</a>
          <a class="btn" href="#">Logout</a>
        {% else %}
          <a class="btn" href="{{ url_for ('users.login_page') }}">Login</a>
        {% endif %}
      </div>
    </nav>
    <div class="content-section">
        {% with messages = get_flashed_messages() %}
          {% if messages %}
            <div class="flashed-messages">
                {% for message in messages %}
                <div class="flashed-message">
                    {{ message }}
                </div>
                {% endfor %}
            </div>
          {% endif %}
        {% endwith %}
        {% block body %}
        {% endblock %}
    </div>
    <div class="footer">
      <p class="footer-text">No copyright here lol :)</p>
    </div>
  </div>
</body>
</html>

winterhut/templates/login.html
{% extends 'layout.html' %}
{% block title %}
    {% if title %}
        {{ title }}
    {% else %}
        Winter's Hut
    {% endif %}
{% endblock %}
{% block body %}
  <div class="login-box">
    <form method="POST" action="">
      {{ form.hidden_tag() }}
      <fieldset>
        <h2>Login</h2>
        <div class="form-field">
          {% if form.email.errors %}
            {{ form.email(placeholder="e-mail address here :)") }}
            <div class="invalid-feedback">
                {% for error in form.email.errors %}
                    <span>{{ error }}</span>
                {% endfor %}
            </div>
          {% else %}
            {{ form.email(placeholder="e-mail address here :)") }}
          {% endif %}
        </div>
        <div class="form-field">
          {{ form.password(placeholder="hunter2 password") }}
        </div>
        <div class="form-field">
          {{ form.submit(class="btn") }}
        </div>
      </fieldset>
    </form>
  </div>
{% endblock %}

winterhut/templates/new_post.html
{% extends "layout.html" %}
{% block title %}
    {% if title %}
        {{ title }}
    {% else %}
        Winter's Hut
    {% endif %}
{% endblock %}
{% block body %}
  <div class="new-post">
    <form method="POST" action="">
      {{ form.hidden_tag() }}
      <fieldset>
        <h2>New Post</h2>
        <div>
          {% if form.title.errors %}
            {{ form.title(class="form-field title", placeholder="Title") }}
            <div class="invalid-feedback">
                {% for error in form.title.errors %}
                    <span>{{ error }}</span>
                {% endfor %}
            </div>
          {% else %}
            {{ form.title(class="form-field title", placeholder="Title") }}
          {% endif %}
        </div>
        <div>
          {% if form.content.errors %}
            {{ form.content(class="form-field content", placeholder="Post body") }}
            <div class="invalid-feedback">
                {% for error in form.content.errors %}
                    <span>{{ error }}</span>
                {% endfor %}
            </div>
          {% else %}
            {{ form.content(class="form-field content", placeholder="Post body") }}
          {% endif %}
        </div>
        <a class="btn" href="{{ url_for('main.home_page') }}">Cancel</a>
        <div>
          {{ form.submit(class="form-field btn") }}
        </div>
        <div>
          {{ form.save_as_draft(class="form-field btn") }}
        </div>
      </fieldset>
    </form>
  </div>
{% endblock %}

winterhut/templates/post.html
{% extends "layout.html" %}
{% block head %}
  <meta property="og:type" content="article">
  <meta property="og:title" content="{{ post.title }} | Winter's Hut">
  <meta property="profile:first_name" content="Dimitar">
  <meta property="profile:last_name" content="Ivanov">
  <meta property="profile:username" content="Winter">
  <meta name="article:author" content="Dimitar Ivanov">
  <meta name="article:published_time" content="{{ post.date_posted.strftime('%Y-%m-%d') }}">
{% endblock %}
{% block title %}
    {% if title %}
        {{ title }}
    {% else %}
        Winter's Hut
    {% endif %}
{% endblock %}
{% block body %}
  <article class="blog-article">
      <a class="article-title">{{ post.title }}</a>
      <small class="article-date-posted">posted at {{ post.date_posted.strftime("%X, %A, %d/%b/%Y") }}</small>
      <div class="article-content">{{ post.content | safe }}</div>
      {% if current_user.is_authenticated %}
        {% if preview != 1 %}
          <div class="article-options">
            <a class="btn" href="{{ url_for('posts.edit_post_page', post_id=post.id)}}">Edit</a>
          </div>
        {% endif %}
      {% endif %}
  </article>
{% endblock %}

winterhut/templates/posts_list.html
{% extends "layout.html" %}
{% block title %}
    {% if title %}
        {{ title }}
    {% else %}
        Winter's Hut
    {% endif %}
{% endblock %}
{% block body %}
  <a class="btn" href="?view=all">All Posts</a>
  <a class="btn" href="?view=drafts">Drafts</a>
  <a class="btn" href="?view=live">Live Posts</a>
  <div class="posts-view">
    {% for post in posts %}
    <article class="article-blob">
      <a class="article-title" href="{{ url_for('posts.view_post_page', post_id=post.id)}}">{{ post.title }}</a>
      <div class="article-options">
        <a class="btn" href="{{ url_for('posts.edit_post_page', post_id=post.id)}}">Edit</a>
      </div>
      {% if post.is_draft == 1 %}
        <small class="article-status">Status: Draft</small>
        <small class="article-date-posted">last updated at {{ post.date_posted.strftime("%X, %A, %d/%b/%Y") }}</small>
      {% else %}
        <small class="article-status">Status: Posted</small>
        <small class="article-date-posted">posted at {{ post.date_posted.strftime("%X, %A, %d/%b/%Y") }}</small>
      {% endif %}
      <div class="article-content">{{ post.content | safe}}</div>
    </article>
    {% endfor %}
  </div>
{% endblock %}